### ISSUE TITLE
Use proper collection types

### ISSUE THREAD

**Issue by cpiotr** [timpeskett/checkyourself#2]
It seems, that `HashMap` is used where `EnumMap` would be sufficient. 
@moncefmechri, @mguby What do you think?
https://github.com/timpeskett/checkyourself/blob/master/core/src/com/timandjake/checkyourself/model/Piece.java#L85

**Comment by mguby** [comment]
Hi all,

I would agree that the use of `eNummAp` would be appropriate here. In case you needed more resources, here are some places with information that you can refer to.

https://docs.oracle.com/javase/7/docs/api/java/util/EnumMap.html
https://www.dotnetperls.com/enummap-java

Thanks,
mguby

**Comment by moncefmechri** [comment]
When in doubt, use this website, it's full of interesting resources:

http://ciruk.pl/

**Comment by timpieces** [comment]
I talked to Gosling and Bloch and they said that EnumMap will be @deprecated in Java 10. Sorry for future-proofing my code...
